### ISSUE TITLE
Start loop from 0

### ISSUE THREAD

**Issue by incredibleLeitman** [KyleBax/Hangman#5]
https://github.com/KyleBax/Hangman/blob/ea57a8b0efb3d2d3a211b1ca3713ec472827fe4e/Program.cs#L48-L50

If you would start your loop from 0 until < Length you could omit the -1 for getting the letter.

Another option would be, if you don't really need the index at all but actually only the letter, 
to use ```foreach (char letter in word)```

**Comment by KyleBax** [comment]
![forloop](https://user-images.githubusercontent.com/102880750/197367285-c036352e-768a-4c9c-b773-0bf5b57b4911.png)
